USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE HEALTHCARE_DB;
USE SCHEMA HEALTHCARE_DB.RAW;

CREATE OR REPLACE TABLE HEALTHCARE_DB.RAW.MASTER_CSV (
    PROVNUM             VARCHAR,
    PROVNAME            VARCHAR,
    CITY                VARCHAR,
    STATE               VARCHAR,
    COUNTY_NAME         VARCHAR,
    COUNTY_FIPS         VARCHAR,
    CY_QTR              VARCHAR,
    WORKDATE            VARCHAR,
    MDSCENSUS           VARCHAR,
    HRS_RNDON           VARCHAR,
    HRS_RNDON_EMP       VARCHAR,
    HRS_RNDON_CTR       VARCHAR,
    HRS_RNADMIN         VARCHAR,
    HRS_RNADMIN_EMP     VARCHAR,
    HRS_RNADMIN_CTR     VARCHAR,
    HRS_RN              VARCHAR,
    HRS_RN_EMP          VARCHAR,
    HRS_RN_CTR          VARCHAR,
    HRS_LPNADMIN        VARCHAR,
    HRS_LPNADMIN_EMP    VARCHAR,
    HRS_LPNADMIN_CTR    VARCHAR,
    HRS_LPN             VARCHAR,
    HRS_LPN_EMP         VARCHAR,
    HRS_LPN_CTR         VARCHAR,
    HRS_CNA             VARCHAR,
    HRS_CNA_EMP         VARCHAR,
    HRS_CNA_CTR         VARCHAR,
    HRS_NATRN           VARCHAR,
    HRS_NATRN_EMP       VARCHAR,
    HRS_NATRN_CTR       VARCHAR,
    HRS_MEDAIDE         VARCHAR,
    HRS_MEDAIDE_EMP     VARCHAR,
    HRS_MEDAIDE_CTR     VARCHAR
);

-- DROP TABLE HEALTHCARE_DB.RAW.MASTER_CSV;

COPY INTO HEALTHCARE_DB.RAW.MASTER_CSV (
    PROVNUM, 
    PROVNAME, 
    CITY, 
    STATE, 
    COUNTY_NAME, 
    COUNTY_FIPS, 
    CY_QTR, 
    WORKDATE, 
    MDSCENSUS,
    HRS_RNDON, 
    HRS_RNDON_EMP, 
    HRS_RNDON_CTR, 
    HRS_RNADMIN, 
    HRS_RNADMIN_EMP, 
    HRS_RNADMIN_CTR,
    HRS_RN, 
    HRS_RN_EMP, 
    HRS_RN_CTR, 
    HRS_LPNADMIN, HRS_LPNADMIN_EMP, HRS_LPNADMIN_CTR,
    HRS_LPN, 
    HRS_LPN_EMP, 
    HRS_LPN_CTR, 
    HRS_CNA, 
    HRS_CNA_EMP, 
    HRS_CNA_CTR,
    HRS_NATRN, 
    HRS_NATRN_EMP, 
    HRS_NATRN_CTR, 
    HRS_MEDAIDE, 
    HRS_MEDAIDE_EMP, 
    HRS_MEDAIDE_CTR
)
FROM @HEALTHCARE_DB.RAW.HEALTHCARE_STAGE
FILES = ('PBJ_Daily_Nurse_Staffing_Q2_2024.csv') -- must indicate respective file for table in s3 bucket
FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM HEALTHCARE_DB.RAW.MASTER_CSV LIMIT 10;
