/*
The RAW Layer serves as an exact, unaltered replica of source data landed in your data warehouse.

Key Characteristics of RAW
Zero Transformation: Maintains 1:1 parity with source CSV files (no column renaming or business logic).

Permissive Data Typing: Every column is stored as VARCHAR to prevent COPY INTO load failures caused by dirty source data.

Lossless Storage: Preserves original payload values so downstream layers can be reprocessed or audited at any time.

Ingestion Metadata: Includes technical tracking fields such as _FILE_NAME, _LOAD_TIMESTAMP, and _FILE_ROW_NUMBER.
*/


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE HEALTHCARE_DB;
USE SCHEMA RAW;

--------------------------------------------------------------------------------
-- 1. RAW_NH_PROVIDER_INFO (103 COLUMNS)
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.RAW_NH_PROVIDER_INFO (
    CMS_CERTIFICATION_NUMBER VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_ADDRESS VARCHAR,
    CITY_TOWN VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,
    TELEPHONE_NUMBER VARCHAR,
    PROVIDER_SSA_COUNTY_CODE VARCHAR,
    COUNTY_PARISH VARCHAR,
    OWNERSHIP_TYPE VARCHAR,
    NUMBER_OF_CERTIFIED_BEDS VARCHAR,
    AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY VARCHAR,
    AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY_FOOTNOTE VARCHAR,
    PROVIDER_TYPE VARCHAR,
    PROVIDER_RESIDES_IN_HOSPITAL VARCHAR,
    LEGAL_BUSINESS_NAME VARCHAR,
    DATE_FIRST_APPROVED_TO_PROVIDE_MEDICARE_AND_MEDICAID_SERVICES VARCHAR,
    AFFILIATED_ENTITY_NAME VARCHAR,
    AFFILIATED_ENTITY_ID VARCHAR,
    CONTINUING_CARE_RETIREMENT_COMMUNITY VARCHAR,
    SPECIAL_FOCUS_STATUS VARCHAR,
    ABUSE_ICON VARCHAR,
    MOST_RECENT_HEALTH_INSPECTION_MORE_THAN_2_YEARS_AGO VARCHAR,
    PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS VARCHAR,
    WITH_A_RESIDENT_AND_FAMILY_COUNCIL VARCHAR,
    AUTOMATIC_SPRINKLER_SYSTEMS_IN_ALL_REQUIRED_AREAS VARCHAR,
    OVERALL_RATING VARCHAR,
    OVERALL_RATING_FOOTNOTE VARCHAR,
    HEALTH_INSPECTION_RATING VARCHAR,
    HEALTH_INSPECTION_RATING_FOOTNOTE VARCHAR,
    QM_RATING VARCHAR,
    QM_RATING_FOOTNOTE VARCHAR,
    LONG_STAY_QM_RATING VARCHAR,
    LONG_STAY_QM_RATING_FOOTNOTE VARCHAR,
    SHORT_STAY_QM_RATING VARCHAR,
    SHORT_STAY_QM_RATING_FOOTNOTE VARCHAR,
    STAFFING_RATING VARCHAR,
    STAFFING_RATING_FOOTNOTE VARCHAR,
    REPORTED_STAFFING_FOOTNOTE VARCHAR,
    PHYSICAL_THERAPIST_STAFFING_FOOTNOTE VARCHAR,
    REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND VARCHAR,
    REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND VARCHAR,
    REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY_ALT VARCHAR,
    TOTAL_NURSING_STAFF_TURNOVER VARCHAR,
    TOTAL_NURSING_STAFF_TURNOVER_FOOTNOTE VARCHAR,
    REGISTERED_NURSE_TURNOVER VARCHAR,
    REGISTERED_NURSE_TURNOVER_FOOTNOTE VARCHAR,
    NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME VARCHAR,
    ADMINISTRATOR_TURNOVER_FOOTNOTE VARCHAR,
    NURSING_CASE_MIX_INDEX VARCHAR,
    NURSING_CASE_MIX_INDEX_RATIO VARCHAR,
    CASE_MIX_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    CASE_MIX_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    CASE_MIX_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    CASE_MIX_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    CASE_MIX_WEEKEND_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    ADJUSTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    ADJUSTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    ADJUSTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    ADJUSTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    ADJUSTED_WEEKEND_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE VARCHAR,
    RATING_CYCLE_1_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_1_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_1_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_1_HEALTH_DEFICIENCY_SCORE VARCHAR,
    RATING_CYCLE_1_NUMBER_OF_HEALTH_REVISITS VARCHAR,
    RATING_CYCLE_1_HEALTH_REVISIT_SCORE VARCHAR,
    RATING_CYCLE_1_TOTAL_HEALTH_SCORE VARCHAR,
    RATING_CYCLE_2_STANDARD_HEALTH_SURVEY_DATE VARCHAR,
    RATING_CYCLE_2_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_2_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_2_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_2_HEALTH_DEFICIENCY_SCORE VARCHAR,
    RATING_CYCLE_2_NUMBER_OF_HEALTH_REVISITS VARCHAR,
    RATING_CYCLE_2_HEALTH_REVISIT_SCORE VARCHAR,
    RATING_CYCLE_2_TOTAL_HEALTH_SCORE VARCHAR,
    RATING_CYCLE_3_STANDARD_HEALTH_SURVEY_DATE VARCHAR,
    RATING_CYCLE_3_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_3_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_3_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES VARCHAR,
    RATING_CYCLE_3_HEALTH_DEFICIENCY_SCORE VARCHAR,
    RATING_CYCLE_3_NUMBER_OF_HEALTH_REVISITS VARCHAR,
    RATING_CYCLE_3_HEALTH_REVISIT_SCORE VARCHAR,
    RATING_CYCLE_3_TOTAL_HEALTH_SCORE VARCHAR,
    TOTAL_WEIGHTED_HEALTH_SURVEY_SCORE VARCHAR,
    NUMBER_OF_FACILITY_REPORTED_INCIDENTS VARCHAR,
    NUMBER_OF_SUBSTANTIATED_COMPLAINTS VARCHAR,
    NUMBER_OF_CITATIONS_FROM_INFECTION_CONTROL_INSPECTIONS VARCHAR,
    NUMBER_OF_FINES VARCHAR,
    TOTAL_AMOUNT_OF_FINES_IN_DOLLARS VARCHAR,
    NUMBER_OF_PAYMENT_DENIALS VARCHAR,
    TOTAL_NUMBER_OF_PENALTIES VARCHAR,
    LOCATION VARCHAR,
    LATITUDE VARCHAR,
    LONGITUDE VARCHAR,
    GEOCODING_FOOTNOTE VARCHAR,
    PROCESSING_DATE VARCHAR
);

COPY INTO RAW.RAW_NH_PROVIDER_INFO
FROM @RAW.HEALTHCARE_STAGE
FILES = ('NH_ProviderInfo_Oct2024.csv')
FILE_FORMAT = (FORMAT_NAME = 'RAW.MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM RAW.RAW_NH_PROVIDER_INFO LIMIT 10;

--------------------------------------------------------------------------------
-- 2. RAW_NH_STATE_US_AVERAGES (48 COLUMNS)
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.RAW_NH_STATE_US_AVERAGES (
    STATE_OR_NATION VARCHAR,
    CYCLE_1_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES VARCHAR,
    CYCLE_1_TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES VARCHAR,
    CYCLE_2_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES VARCHAR,
    CYCLE_2_TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES VARCHAR,
    CYCLE_3_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES VARCHAR,
    CYCLE_3_TOTAL_NUMBER_OF_FIRE_SAFETY_DEFICIENCIES VARCHAR,
    AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY VARCHAR,
    REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND VARCHAR,
    REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND VARCHAR,
    REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    TOTAL_NURSING_STAFF_TURNOVER VARCHAR,
    REGISTERED_NURSE_TURNOVER VARCHAR,
    NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME VARCHAR,
    NURSING_CASE_MIX_INDEX VARCHAR,
    CASE_MIX_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    CASE_MIX_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    CASE_MIX_WEEKEND_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY VARCHAR,
    NUMBER_OF_FINES VARCHAR,
    FINE_AMOUNT_IN_DOLLARS VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHOSE_NEED_FOR_HELP_WITH_DAILY_ACTIVITIES_HAS_INCREASED VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHO_LOSE_TOO_MUCH_WEIGHT VARCHAR,
    PERCENTAGE_OF_LOW_RISK_LONG_STAY_RESIDENTS_WHO_LOSE_CONTROL_OF_THEIR_BOWELS_OR_BLADDER VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WITH_A_CATHETER_INSERTED_AND_LEFT_IN_THEIR_BLADDER VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WITH_A_URINARY_TRACT_INFECTION VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHO_HAVE_DEPRESSIVE_SYMPTOMS VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHO_WERE_PHYSICALLY_RESTRAINED VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_EXPERIENCING_ONE_OR_MORE_FALLS_WITH_MAJOR_INJURY VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_ASSESSED_AND_APPROPRIATELY_GIVEN_THE_PNEUMOCOCCAL_VACCINE VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHO_RECEIVED_AN_ANTIPSYCHOTIC_MEDICATION VARCHAR,
    PERCENTAGE_OF_SHORT_STAY_RESIDENTS_ASSESSED_AND_APPROPRIATELY_GIVEN_THE_PNEUMOCOCCAL_VACCINE VARCHAR,
    PERCENTAGE_OF_SHORT_STAY_RESIDENTS_WHO_NEWLY_RECEIVED_AN_ANTIPSYCHOTIC_MEDICATION VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHOSE_ABILITY_TO_MOVE_INDEPENDENTLY_WORSENED VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_WHO_RECEIVED_AN_ANTIANXIETY_OR_HYPNOTIC_MEDICATION VARCHAR,
    PERCENTAGE_OF_HIGH_RISK_LONG_STAY_RESIDENTS_WITH_PRESSURE_ULCERS VARCHAR,
    PERCENTAGE_OF_LONG_STAY_RESIDENTS_ASSESSED_AND_APPROPRIATELY_GIVEN_THE_SEASONAL_INFLUENZA_VACCINE VARCHAR,
    PERCENTAGE_OF_SHORT_STAY_RESIDENTS_WHO_MADE_IMPROVEMENTS_IN_FUNCTION VARCHAR,
    PERCENTAGE_OF_SHORT_STAY_RESIDENTS_WHO_WERE_ASSESSED_AND_APPROPRIATELY_GIVEN_THE_SEASONAL_INFLUENZA_VACCINE VARCHAR,
    PERCENTAGE_OF_SHORT_STAY_RESIDENTS_WHO_WERE_REHOSPITALIZED_AFTER_A_NURSING_HOME_ADMISSION VARCHAR,
    PERCENTAGE_OF_SHORT_STAY_RESIDENTS_WHO_HAD_AN_OUTPATIENT_EMERGENCY_DEPARTMENT_VISIT VARCHAR,
    NUMBER_OF_HOSPITALIZATIONS_PER_1000_LONG_STAY_RESIDENT_DAYS VARCHAR,
    NUMBER_OF_OUTPATIENT_EMERGENCY_DEPARTMENT_VISITS_PER_1000_LONG_STAY_RESIDENT_DAYS VARCHAR,
    PROCESSING_DATE VARCHAR
);

COPY INTO RAW.RAW_NH_STATE_US_AVERAGES
FROM @RAW.HEALTHCARE_STAGE
FILES = ('NH_StateUSAverages_Oct2024.csv')
FILE_FORMAT = (FORMAT_NAME = 'RAW.MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM RAW.RAW_NH_STATE_US_AVERAGES LIMIT 10;

--------------------------------------------------------------------------------
-- 3. RAW_NH_QUALITY_MSR_CLAIMS (17 COLUMNS)
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.RAW_NH_QUALITY_MSR_CLAIMS (
    CMS_CERTIFICATION_NUMBER VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_ADDRESS VARCHAR,
    CITY_TOWN VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,
    MEASURE_CODE VARCHAR,
    MEASURE_DESCRIPTION VARCHAR,
    RESIDENT_TYPE VARCHAR,
    ADJUSTED_SCORE VARCHAR,
    OBSERVED_SCORE VARCHAR,
    EXPECTED_SCORE VARCHAR,
    FOOTNOTE_FOR_SCORE VARCHAR,
    USED_IN_QUALITY_MEASURE_FIVE_STAR_RATING VARCHAR,
    MEASURE_PERIOD VARCHAR,
    LOCATION VARCHAR,
    PROCESSING_DATE VARCHAR
);

COPY INTO RAW.RAW_NH_QUALITY_MSR_CLAIMS
FROM @RAW.HEALTHCARE_STAGE
FILES = ('NH_QualityMsr_Claims_Oct2024.csv')
FILE_FORMAT = (FORMAT_NAME = 'RAW.MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM RAW.RAW_NH_QUALITY_MSR_CLAIMS LIMIT 10;

--------------------------------------------------------------------------------
-- 4. RAW_SNF_VBP_PERFORMANCE (9 COLUMNS)
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.RAW_SNF_VBP_PERFORMANCE (
    BASELINE_PERIOD_FY_2019_NATIONAL_AVERAGE_READMISSION_RATE VARCHAR,
    PERFORMANCE_PERIOD_FY_2022_NATIONAL_AVERAGE_READMISSION_RATE VARCHAR,
    FY_2024_ACHIEVEMENT_THRESHOLD VARCHAR,
    FY_2024_BENCHMARK VARCHAR,
    RANGE_OF_PERFORMANCE_SCORES VARCHAR,
    TOTAL_NUMBER_OF_SNFS_RECEIVING_VALUE_BASED_INCENTIVE_PAYMENTS VARCHAR,
    RANGE_OF_INCENTIVE_PAYMENT_MULTIPLIERS VARCHAR,
    RANGE_OF_VALUE_BASED_INCENTIVE_PAYMENTS_DOLLARS VARCHAR,
    TOTAL_AMOUNT_OF_VALUE_BASED_INCENTIVE_PAYMENTS_DOLLARS VARCHAR
);

COPY INTO RAW.RAW_SNF_VBP_PERFORMANCE
FROM @RAW.HEALTHCARE_STAGE
FILES = ('FY_2024_SNF_VBP_Aggregate_Performance.csv')
FILE_FORMAT = (FORMAT_NAME = 'RAW.MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM RAW.RAW_SNF_VBP_PERFORMANCE LIMIT 10;

--------------------------------------------------------------------------------
-- 5. RAW_NH_PENALTIES (13 COLUMNS)
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.RAW_NH_PENALTIES (
    CMS_CERTIFICATION_NUMBER VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_ADDRESS VARCHAR,
    CITY_TOWN VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,
    PENALTY_DATE VARCHAR,
    PENALTY_TYPE VARCHAR,
    FINE_AMOUNT VARCHAR,
    PAYMENT_DENIAL_START_DATE VARCHAR,
    PAYMENT_DENIAL_LENGTH_IN_DAYS VARCHAR,
    LOCATION VARCHAR,
    PROCESSING_DATE VARCHAR
);

COPY INTO RAW.RAW_NH_PENALTIES
FROM @RAW.HEALTHCARE_STAGE
FILES = ('NH_Penalties_Oct2024.csv')
FILE_FORMAT = (FORMAT_NAME = 'RAW.MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM RAW.RAW_NH_PENALTIES LIMIT 10;

--------------------------------------------------------------------------------
-- 6. RAW_NH_HEALTH_CITATIONS (23 COLUMNS)
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.RAW_NH_HEALTH_CITATIONS (
    CMS_CERTIFICATION_NUMBER VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_ADDRESS VARCHAR,
    CITY_TOWN VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,
    SURVEY_DATE VARCHAR,
    SURVEY_TYPE VARCHAR,
    DEFICIENCY_PREFIX VARCHAR,
    DEFICIENCY_TAG_NUMBER VARCHAR,
    DEFICIENCY_DESCRIPTION VARCHAR,
    SCOPE_SEVERITY_CODE VARCHAR,
    DEFICIENCY_CORRECTED VARCHAR,
    CORRECTION_DATE VARCHAR,
    INSPECTION_CYCLE VARCHAR,
    STANDARD_DEFICIENCIES VARCHAR,
    COMPLAINT_DEFICIENCIES VARCHAR,
    INFECTION_CONTROL_DEFICIENCIES VARCHAR,
    LOCATION VARCHAR,
    LATITUDE VARCHAR,
    LONGITUDE VARCHAR,
    GEOCODING_FOOTNOTE VARCHAR,
    PROCESSING_DATE VARCHAR
);

COPY INTO RAW.RAW_NH_HEALTH_CITATIONS
FROM @RAW.HEALTHCARE_STAGE
FILES = ('NH_HealthCitations_Oct2024.csv')
FILE_FORMAT = (FORMAT_NAME = 'RAW.MY_CSV_FORMAT')
ON_ERROR = 'SKIP_FILE';

SELECT * FROM RAW.RAW_NH_HEALTH_CITATIONS LIMIT 10;



