/*
The Bronze Layer acts as the cleansed, strongly typed, and standardized data lake foundation.

Key Transformations in Bronze
Schema & Naming Standard: Rename raw long string headers to standard SNAKE_CASE.

Type Casting: Convert text strings from RAW into proper data types (INT, FLOAT, DATE, BOOLEAN).

Audit Lineage Metadata: Add _INGESTED_AT, _SOURCE_FILE, and _ROW_ID columns for data lineage and tracking.
*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE HEALTHCARE_DB;
USE SCHEMA BRONZE;

--------------------------------------------------------------------------------
-- 1. BRONZE_NH_PROVIDER_INFO
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.BRONZE_NH_PROVIDER_INFO AS
SELECT
    -- Identifiers & Demographics
    CMS_CERTIFICATION_NUMBER                        AS CCN,
    PROVIDER_NAME,
    PROVIDER_ADDRESS,
    CITY_TOWN                                       AS CITY,
    STATE,
    ZIP_CODE,
    TELEPHONE_NUMBER,
    PROVIDER_SSA_COUNTY_CODE                        AS SSA_COUNTY_CODE,
    COUNTY_PARISH                                   AS COUNTY,
    OWNERSHIP_TYPE,
    TRY_CAST(NUMBER_OF_CERTIFIED_BEDS AS INT)       AS CERTIFIED_BEDS,
    TRY_CAST(AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY AS FLOAT) AS AVG_RESIDENTS_PER_DAY,
    AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY_FOOTNOTE    AS AVG_RESIDENTS_FOOTNOTE,
    PROVIDER_TYPE,
    IFF(UPPER(PROVIDER_RESIDES_IN_HOSPITAL) = 'Y', TRUE, FALSE) AS IS_HOSPITAL_BASED,
    LEGAL_BUSINESS_NAME,
    TRY_CAST(DATE_FIRST_APPROVED_TO_PROVIDE_MEDICARE_AND_MEDICAID_SERVICES AS DATE) AS MEDICARE_MEDICAID_APPROVAL_DATE,
    AFFILIATED_ENTITY_NAME,
    AFFILIATED_ENTITY_ID,
    IFF(UPPER(CONTINUING_CARE_RETIREMENT_COMMUNITY) = 'Y', TRUE, FALSE) AS IS_CCRC,
    SPECIAL_FOCUS_STATUS,
    IFF(UPPER(ABUSE_ICON) = 'Y', TRUE, FALSE)        AS HAS_ABUSE_ICON,
    IFF(UPPER(MOST_RECENT_HEALTH_INSPECTION_MORE_THAN_2_YEARS_AGO) = 'Y', TRUE, FALSE) AS INSPECTION_OVER_2_YEARS,
    IFF(UPPER(PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS) = 'Y', TRUE, FALSE) AS CHANGED_OWNERSHIP_LAST_12M,
    IFF(UPPER(WITH_A_RESIDENT_AND_FAMILY_COUNCIL) = 'Y', TRUE, FALSE) AS HAS_RESIDENT_FAMILY_COUNCIL,
    IFF(UPPER(AUTOMATIC_SPRINKLER_SYSTEMS_IN_ALL_REQUIRED_AREAS) = 'Y', TRUE, FALSE) AS HAS_ALL_SPRINKLERS,

    -- Ratings (1-5 Stars)
    TRY_CAST(OVERALL_RATING AS INT)                 AS OVERALL_RATING,
    OVERALL_RATING_FOOTNOTE,
    TRY_CAST(HEALTH_INSPECTION_RATING AS INT)       AS HEALTH_INSPECTION_RATING,
    HEALTH_INSPECTION_RATING_FOOTNOTE,
    TRY_CAST(QM_RATING AS INT)                      AS QM_RATING,
    QM_RATING_FOOTNOTE,
    TRY_CAST(LONG_STAY_QM_RATING AS INT)            AS LONG_STAY_QM_RATING,
    LONG_STAY_QM_RATING_FOOTNOTE,
    TRY_CAST(SHORT_STAY_QM_RATING AS INT)           AS SHORT_STAY_QM_RATING,
    SHORT_STAY_QM_RATING_FOOTNOTE,
    TRY_CAST(STAFFING_RATING AS INT)                AS STAFFING_RATING,
    STAFFING_RATING_FOOTNOTE,

    -- Staffing Hours per Resident Day (HPRD)
    TRY_CAST(REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT) AS REPORTED_NURSE_AIDE_HPRD,
    TRY_CAST(REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)        AS REPORTED_LPN_HPRD,
    TRY_CAST(REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)         AS REPORTED_RN_HPRD,
    TRY_CAST(REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)   AS REPORTED_LICENSED_HPRD,
    TRY_CAST(REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT) AS REPORTED_TOTAL_NURSE_HPRD,
    TRY_CAST(TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND AS FLOAT) AS REPORTED_WEEKEND_TOTAL_NURSE_HPRD,
    TRY_CAST(REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND AS FLOAT) AS REPORTED_WEEKEND_RN_HPRD,
    TRY_CAST(REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY_ALT AS FLOAT) AS REPORTED_PT_HPRD,

    -- Staffing Turnover
    TRY_CAST(TOTAL_NURSING_STAFF_TURNOVER AS FLOAT)  AS NURSING_STAFF_TURNOVER_PCT,
    TOTAL_NURSING_STAFF_TURNOVER_FOOTNOTE,
    TRY_CAST(REGISTERED_NURSE_TURNOVER AS FLOAT)     AS RN_TURNOVER_PCT,
    REGISTERED_NURSE_TURNOVER_FOOTNOTE,
    TRY_CAST(NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME AS INT) AS ADMINISTRATORS_DEPARTED,
    ADMINISTRATOR_TURNOVER_FOOTNOTE,

    -- Case-Mix & Adjusted Staffing
    TRY_CAST(NURSING_CASE_MIX_INDEX AS FLOAT)        AS NURSING_CASE_MIX_INDEX,
    TRY_CAST(NURSING_CASE_MIX_INDEX_RATIO AS FLOAT)  AS NURSING_CASE_MIX_INDEX_RATIO,
    TRY_CAST(ADJUSTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT) AS ADJUSTED_NURSE_AIDE_HPRD,
    TRY_CAST(ADJUSTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)        AS ADJUSTED_LPN_HPRD,
    TRY_CAST(ADJUSTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)         AS ADJUSTED_RN_HPRD,
    TRY_CAST(ADJUSTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT) AS ADJUSTED_TOTAL_NURSE_HPRD,

    -- Inspection & Health Deficiencies Metrics
    TRY_CAST(TOTAL_WEIGHTED_HEALTH_SURVEY_SCORE AS FLOAT) AS TOTAL_WEIGHTED_HEALTH_SURVEY_SCORE,
    TRY_CAST(NUMBER_OF_FACILITY_REPORTED_INCIDENTS AS INT) AS REPORTED_INCIDENTS_COUNT,
    TRY_CAST(NUMBER_OF_SUBSTANTIATED_COMPLAINTS AS INT) AS SUBSTANTIATED_COMPLAINTS_COUNT,
    TRY_CAST(NUMBER_OF_FINES AS INT)                 AS FINES_COUNT,
    TRY_CAST(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS AS FLOAT) AS TOTAL_FINE_AMOUNT,
    TRY_CAST(NUMBER_OF_PAYMENT_DENIALS AS INT)       AS PAYMENT_DENIALS_COUNT,
    TRY_CAST(TOTAL_NUMBER_OF_PENALTIES AS INT)       AS PENALTIES_COUNT,

    -- Location & Metadata
    LOCATION,
    TRY_CAST(LATITUDE AS FLOAT)                      AS LATITUDE,
    TRY_CAST(LONGITUDE AS FLOAT)                     AS LONGITUDE,
    TRY_CAST(PROCESSING_DATE AS DATE)                AS PROCESSING_DATE,
    
    -- Audit Metadata
    CURRENT_TIMESTAMP()                              AS _INGESTED_AT,
    'NH_ProviderInfo_Oct2024.csv'                    AS _SOURCE_FILE
FROM RAW.RAW_NH_PROVIDER_INFO;


--------------------------------------------------------------------------------
-- 2. BRONZE_NH_STATE_US_AVERAGES
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.BRONZE_NH_STATE_US_AVERAGES AS
SELECT
    STATE_OR_NATION,
    TRY_CAST(AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY AS FLOAT) AS AVG_RESIDENTS_PER_DAY,
    TRY_CAST(REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT) AS REPORTED_NURSE_AIDE_HPRD,
    TRY_CAST(REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)        AS REPORTED_LPN_HPRD,
    TRY_CAST(REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)         AS REPORTED_RN_HPRD,
    TRY_CAST(REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT)   AS REPORTED_LICENSED_HPRD,
    TRY_CAST(REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY AS FLOAT) AS REPORTED_TOTAL_NURSE_HPRD,
    TRY_CAST(TOTAL_NURSING_STAFF_TURNOVER AS FLOAT)  AS NURSING_STAFF_TURNOVER_PCT,
    TRY_CAST(REGISTERED_NURSE_TURNOVER AS FLOAT)     AS RN_TURNOVER_PCT,
    TRY_CAST(NUMBER_OF_FINES AS INT)                 AS AVG_FINES_COUNT,
    TRY_CAST(FINE_AMOUNT_IN_DOLLARS AS FLOAT)        AS AVG_FINE_AMOUNT,
    TRY_CAST(PROCESSING_DATE AS DATE)                AS PROCESSING_DATE,
    CURRENT_TIMESTAMP()                              AS _INGESTED_AT,
    'NH_StateUSAverages_Oct2024.csv'                 AS _SOURCE_FILE
FROM RAW.RAW_NH_STATE_US_AVERAGES;


--------------------------------------------------------------------------------
-- 3. BRONZE_NH_QUALITY_MSR_CLAIMS
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.BRONZE_NH_QUALITY_MSR_CLAIMS AS
SELECT
    CMS_CERTIFICATION_NUMBER                         AS CCN,
    PROVIDER_NAME,
    PROVIDER_ADDRESS,
    CITY_TOWN                                        AS CITY,
    STATE,
    ZIP_CODE,
    MEASURE_CODE,
    MEASURE_DESCRIPTION,
    RESIDENT_TYPE,
    TRY_CAST(ADJUSTED_SCORE AS FLOAT)                AS ADJUSTED_SCORE,
    TRY_CAST(OBSERVED_SCORE AS FLOAT)                AS OBSERVED_SCORE,
    TRY_CAST(EXPECTED_SCORE AS FLOAT)                AS EXPECTED_SCORE,
    FOOTNOTE_FOR_SCORE,
    IFF(UPPER(USED_IN_QUALITY_MEASURE_FIVE_STAR_RATING) = 'Y', TRUE, FALSE) AS IS_USED_IN_5STAR_RATING,
    MEASURE_PERIOD,
    LOCATION,
    TRY_CAST(PROCESSING_DATE AS DATE)                AS PROCESSING_DATE,
    CURRENT_TIMESTAMP()                              AS _INGESTED_AT,
    'NH_QualityMsr_Claims_Oct2024.csv'              AS _SOURCE_FILE
FROM RAW.RAW_NH_QUALITY_MSR_CLAIMS;


--------------------------------------------------------------------------------
-- 4. BRONZE_SNF_VBP_PERFORMANCE
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.BRONZE_SNF_VBP_PERFORMANCE AS
SELECT
    TRY_CAST(BASELINE_PERIOD_FY_2019_NATIONAL_AVERAGE_READMISSION_RATE AS FLOAT)    AS BASELINE_2019_READMISSION_RATE,
    TRY_CAST(PERFORMANCE_PERIOD_FY_2022_NATIONAL_AVERAGE_READMISSION_RATE AS FLOAT) AS PERFORMANCE_2022_READMISSION_RATE,
    TRY_CAST(FY_2024_ACHIEVEMENT_THRESHOLD AS FLOAT) AS FY2024_ACHIEVEMENT_THRESHOLD,
    TRY_CAST(FY_2024_BENCHMARK AS FLOAT)             AS FY2024_BENCHMARK,
    RANGE_OF_PERFORMANCE_SCORES,
    TRY_CAST(TOTAL_NUMBER_OF_SNFS_RECEIVING_VALUE_BASED_INCENTIVE_PAYMENTS AS INT) AS TOTAL_SNFS_RECEIVING_INCENTIVE,
    RANGE_OF_INCENTIVE_PAYMENT_MULTIPLIERS,
    RANGE_OF_VALUE_BASED_INCENTIVE_PAYMENTS_DOLLARS  AS INCENTIVE_PAYMENTS_RANGE_DOLLARS,
    TRY_CAST(REPLACE(REPLACE(TOTAL_AMOUNT_OF_VALUE_BASED_INCENTIVE_PAYMENTS_DOLLARS, '$', ''), ',', '') AS FLOAT) AS TOTAL_INCENTIVE_PAYMENTS_DOLLARS,
    CURRENT_TIMESTAMP()                              AS _INGESTED_AT,
    'FY_2024_SNF_VBP_Aggregate_Performance.csv'     AS _SOURCE_FILE
FROM RAW.RAW_SNF_VBP_PERFORMANCE;


--------------------------------------------------------------------------------
-- 5. BRONZE_NH_PENALTIES
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.BRONZE_NH_PENALTIES AS
SELECT
    CMS_CERTIFICATION_NUMBER                         AS CCN,
    PROVIDER_NAME,
    PROVIDER_ADDRESS,
    CITY_TOWN                                        AS CITY,
    STATE,
    ZIP_CODE,
    TRY_CAST(PENALTY_DATE AS DATE)                   AS PENALTY_DATE,
    PENALTY_TYPE,
    TRY_CAST(FINE_AMOUNT AS FLOAT)                   AS FINE_AMOUNT,
    TRY_CAST(PAYMENT_DENIAL_START_DATE AS DATE)      AS PAYMENT_DENIAL_START_DATE,
    TRY_CAST(PAYMENT_DENIAL_LENGTH_IN_DAYS AS INT)   AS PAYMENT_DENIAL_LENGTH_DAYS,
    LOCATION,
    TRY_CAST(PROCESSING_DATE AS DATE)                AS PROCESSING_DATE,
    CURRENT_TIMESTAMP()                              AS _INGESTED_AT,
    'NH_Penalties_Oct2024.csv'                       AS _SOURCE_FILE
FROM RAW.RAW_NH_PENALTIES;


--------------------------------------------------------------------------------
-- 6. BRONZE_NH_HEALTH_CITATIONS
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE BRONZE.BRONZE_NH_HEALTH_CITATIONS AS
SELECT
    CMS_CERTIFICATION_NUMBER                         AS CCN,
    PROVIDER_NAME,
    PROVIDER_ADDRESS,
    CITY_TOWN                                        AS CITY,
    STATE,
    ZIP_CODE,
    TRY_CAST(SURVEY_DATE AS DATE)                    AS SURVEY_DATE,
    SURVEY_TYPE,
    DEFICIENCY_PREFIX,
    DEFICIENCY_TAG_NUMBER,
    DEFICIENCY_DESCRIPTION,
    SCOPE_SEVERITY_CODE,
    IFF(UPPER(DEFICIENCY_CORRECTED) = 'Y', TRUE, FALSE) AS IS_DEFICIENCY_CORRECTED,
    TRY_CAST(CORRECTION_DATE AS DATE)                AS CORRECTION_DATE,
    INSPECTION_CYCLE,
    TRY_CAST(STANDARD_DEFICIENCIES AS INT)           AS STANDARD_DEFICIENCIES,
    TRY_CAST(COMPLAINT_DEFICIENCIES AS INT)          AS COMPLAINT_DEFICIENCIES,
    TRY_CAST(INFECTION_CONTROL_DEFICIENCIES AS INT)  AS INFECTION_CONTROL_DEFICIENCIES,
    LOCATION,
    TRY_CAST(LATITUDE AS FLOAT)                      AS LATITUDE,
    TRY_CAST(LONGITUDE AS FLOAT)                     AS LONGITUDE,
    GEOCODING_FOOTNOTE,
    TRY_CAST(PROCESSING_DATE AS DATE)                AS PROCESSING_DATE,
    CURRENT_TIMESTAMP()                              AS _INGESTED_AT,
    'NH_HealthCitations_Oct2024.csv'                 AS _SOURCE_FILE
FROM RAW.RAW_NH_HEALTH_CITATIONS;