-- ============================================================================
-- STEP 1: CREATE BRONZE SCHEMA
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE HEALTHCARE_DB;
CREATE OR REPLACE SCHEMA HEALTHCARE_DB.BRONZE;


-- ============================================================================
-- STEP 2: CREATE BRONZE STAGING TABLE
-- ============================================================================
CREATE OR REPLACE TABLE HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE (
    HASH_ID             VARCHAR(64) PRIMARY KEY,
    PROVNUM             VARCHAR,
    PROVNAME            VARCHAR,
    CITY                VARCHAR,
    STATE               VARCHAR,
    COUNTY_NAME         VARCHAR,
    COUNTY_FIPS         VARCHAR,
    CY_QTR              VARCHAR,
    WORKDATE            VARCHAR,
    MDSCENSUS           VARCHAR,
    HRS_RNDON           VARCHAR,
    HRS_RNDON_EMP       VARCHAR,
    HRS_RNDON_CTR       VARCHAR,
    HRS_RNADMIN         VARCHAR,
    HRS_RNADMIN_EMP     VARCHAR,
    HRS_RNADMIN_CTR     VARCHAR,
    HRS_RN              VARCHAR,
    HRS_RN_EMP          VARCHAR,
    HRS_RN_CTR          VARCHAR,
    HRS_LPNADMIN        VARCHAR,
    HRS_LPNADMIN_EMP    VARCHAR,
    HRS_LPNADMIN_CTR    VARCHAR,
    HRS_LPN             VARCHAR,
    HRS_LPN_EMP         VARCHAR,
    HRS_LPN_CTR         VARCHAR,
    HRS_CNA             VARCHAR,
    HRS_CNA_EMP         VARCHAR,
    HRS_CNA_CTR         VARCHAR,
    HRS_NATRN           VARCHAR,
    HRS_NATRN_EMP       VARCHAR,
    HRS_NATRN_CTR       VARCHAR,
    HRS_MEDAIDE         VARCHAR,
    HRS_MEDAIDE_EMP     VARCHAR,
    HRS_MEDAIDE_CTR     VARCHAR,
    _SOURCE_FILE        VARCHAR,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- ============================================================================
-- STEP 3: INGEST FROM RAW TO BRONZE (WITH SANITIZATION & METADATA)
-- ============================================================================
INSERT INTO HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE (
    HASH_ID,
    PROVNUM, 
    PROVNAME, 
    CITY, 
    STATE, 
    COUNTY_NAME, 
    COUNTY_FIPS, 
    CY_QTR, 
    WORKDATE, 
    MDSCENSUS,
    HRS_RNDON, 
    HRS_RNDON_EMP, 
    HRS_RNDON_CTR, 
    HRS_RNADMIN, 
    HRS_RNADMIN_EMP, 
    HRS_RNADMIN_CTR,
    HRS_RN, 
    HRS_RN_EMP, 
    HRS_RN_CTR, 
    HRS_LPNADMIN, HRS_LPNADMIN_EMP, HRS_LPNADMIN_CTR,
    HRS_LPN, 
    HRS_LPN_EMP, 
    HRS_LPN_CTR, 
    HRS_CNA, 
    HRS_CNA_EMP, 
    HRS_CNA_CTR,
    HRS_NATRN, 
    HRS_NATRN_EMP, 
    HRS_NATRN_CTR, 
    HRS_MEDAIDE, 
    HRS_MEDAIDE_EMP, 
    HRS_MEDAIDE_CTR,
    _SOURCE_FILE
)
SELECT 
    -- Primary Key: Hash composed of Provider ID + Work Date
    MD5(CONCAT_WS('|', COALESCE(TRIM(PROVNUM), ''), COALESCE(TRIM(WORKDATE), ''))),
    TRIM(PROVNUM),
    UPPER(TRIM(PROVNAME)),
    UPPER(TRIM(CITY)),
    UPPER(TRIM(STATE)),
    UPPER(TRIM(COUNTY_NAME)),
    TRIM(COUNTY_FIPS),
    TRIM(CY_QTR),
    TRIM(WORKDATE),
    TRIM(MDSCENSUS),
    TRIM(HRS_RNDON),
    TRIM(HRS_RNDON_EMP),
    TRIM(HRS_RNDON_CTR),
    TRIM(HRS_RNADMIN),
    TRIM(HRS_RNADMIN_EMP),
    TRIM(HRS_RNADMIN_CTR),
    TRIM(HRS_RN),
    TRIM(HRS_RN_EMP),
    TRIM(HRS_RN_CTR),
    TRIM(HRS_LPNADMIN),
    TRIM(HRS_LPNADMIN_EMP),
    TRIM(HRS_LPNADMIN_CTR),
    TRIM(HRS_LPN),
    TRIM(HRS_LPN_EMP),
    TRIM(HRS_LPN_CTR),
    TRIM(HRS_CNA),
    TRIM(HRS_CNA_EMP),
    TRIM(HRS_CNA_CTR),
    TRIM(HRS_NATRN),
    TRIM(HRS_NATRN_EMP),
    TRIM(HRS_NATRN_CTR),
    TRIM(HRS_MEDAIDE),
    TRIM(HRS_MEDAIDE_EMP),
    TRIM(HRS_MEDAIDE_CTR),
    'PBJ_Daily_Nurse_Staffing_Q2_2024.csv'
FROM HEALTHCARE_DB.RAW.MASTER_CSV;

SELECT * FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE LIMIT 10;


-- ============================================================================
-- STEP 4: BRONZE DATA QUALITY AUDIT CHECKS
-- ============================================================================

-- Audit 4A: Missing & Null Value Analysis
SELECT
    COUNT(*) AS TOTAL_BRONZE_ROWS,
    -- Core Identifiers
    SUM(CASE WHEN PROVNUM IS NULL OR PROVNUM = '' THEN 1 ELSE 0 END) AS MISSING_PROVNUM,
    SUM(CASE WHEN PROVNAME IS NULL OR PROVNAME = '' THEN 1 ELSE 0 END) AS MISSING_PROVNAME,
    SUM(CASE WHEN STATE IS NULL OR STATE = '' THEN 1 ELSE 0 END) AS MISSING_STATE,
    -- Dates & Patient Census
    SUM(CASE WHEN WORKDATE IS NULL OR WORKDATE = '' THEN 1 ELSE 0 END) AS MISSING_WORKDATE,
    SUM(CASE WHEN CY_QTR IS NULL OR CY_QTR = '' THEN 1 ELSE 0 END) AS MISSING_CY_QTR,
    SUM(CASE WHEN MDSCENSUS IS NULL OR MDSCENSUS = '' THEN 1 ELSE 0 END) AS MISSING_MDSCENSUS,
    -- Primary Hours Metrics
    SUM(CASE WHEN HRS_RN IS NULL OR HRS_RN = '' THEN 1 ELSE 0 END) AS MISSING_HRS_RN,
    SUM(CASE WHEN HRS_LPN IS NULL OR HRS_LPN = '' THEN 1 ELSE 0 END) AS MISSING_HRS_LPN,
    SUM(CASE WHEN HRS_CNA IS NULL OR HRS_CNA = '' THEN 1 ELSE 0 END) AS MISSING_HRS_CNA
FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE;


-- Audit 4B: Duplicate Identification
-- Check Hash Primary Key Collisions
SELECT 
    HASH_ID, 
    COUNT(*) AS HASH_COUNT 
FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE 
GROUP BY HASH_ID 
HAVING COUNT(*) > 1;

-- Check Duplicate Business Keys (Multiple logs for the same provider on the same day)
SELECT 
    PROVNUM, 
    WORKDATE, 
    COUNT(*) AS DUPLICATE_DAILY_LOGS
FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE
GROUP BY PROVNUM, WORKDATE
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_DAILY_LOGS DESC;


-- Audit 4C: Outliers & String Conversion Anomalies
SELECT
    -- Detect non-numeric text inside metric columns (e.g., 'N/A', 'UNKNOWN')
    SUM(CASE WHEN TRY_CAST(MDSCENSUS AS FLOAT) IS NULL AND MDSCENSUS IS NOT NULL THEN 1 ELSE 0 END) AS INVALID_CENSUS_STRINGS,
    SUM(CASE WHEN TRY_CAST(HRS_RN AS FLOAT) IS NULL AND HRS_RN IS NOT NULL THEN 1 ELSE 0 END) AS INVALID_RN_HOURS_STRINGS,
    
    -- Negative Values
    SUM(CASE WHEN TRY_CAST(MDSCENSUS AS FLOAT) < 0 THEN 1 ELSE 0 END) AS NEGATIVE_CENSUS_COUNT,
    SUM(CASE WHEN TRY_CAST(HRS_RN AS FLOAT) < 0 THEN 1 ELSE 0 END) AS NEGATIVE_RN_HOURS,
    SUM(CASE WHEN TRY_CAST(HRS_CNA AS FLOAT) < 0 THEN 1 ELSE 0 END) AS NEGATIVE_CNA_HOURS,
    
    -- Zero Census
    SUM(CASE WHEN TRY_CAST(MDSCENSUS AS FLOAT) = 0 THEN 1 ELSE 0 END) AS ZERO_CENSUS_COUNT,
    
    -- Unusually High Outliers for 1 Facility Day
    SUM(CASE WHEN TRY_CAST(MDSCENSUS AS FLOAT) > 1000 THEN 1 ELSE 0 END) AS CENSUS_OVER_1000,
    SUM(CASE WHEN TRY_CAST(HRS_RN AS FLOAT) > 500 THEN 1 ELSE 0 END) AS RN_HOURS_OVER_500_DAY,
    SUM(CASE WHEN TRY_CAST(HRS_CNA AS FLOAT) > 1000 THEN 1 ELSE 0 END) AS CNA_HOURS_OVER_1000_DAY
FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE;