-- ============================================================================
-- STEP 1: CREATE SILVER SCHEMA
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.SILVER;


-- ============================================================================
-- STEP 2: BUILD SILVER_MASTER_DIM_PROVIDER (DIMENSION TABLE)
-- ============================================================================
CREATE OR REPLACE TABLE HEALTHCARE_DB.SILVER.SILVER_MASTER_DIM_PROVIDER AS
SELECT
    PROVNUM AS PROVIDER_ID,
    PROVNAME AS PROVIDER_NAME,
    CITY,
    STATE,
    COUNTY_NAME,
    COUNTY_FIPS,
    CURRENT_TIMESTAMP() AS _UPDATED_AT
FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE
WHERE PROVNUM IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY PROVNUM ORDER BY _LOADED_AT DESC) = 1;


-- ============================================================================
-- STEP 3: BUILD FACT_DAILY_STAFFING (FACT TABLE)
-- ============================================================================
CREATE OR REPLACE TABLE HEALTHCARE_DB.SILVER.SILVER_MASTER_FACT_DAILY_STAFFING AS
SELECT
    HASH_ID,
    TRIM(PROVNUM) AS PROVIDER_ID,
    
    -- Date conversions
    TRY_TO_DATE(WORKDATE, 'YYYYMMDD') AS WORK_DATE,
    TRIM(CY_QTR) AS CALENDAR_QUARTER,
    
    -- Resident Census
    COALESCE(TRY_CAST(MDSCENSUS AS NUMBER), 0) AS RESIDENT_CENSUS,
    
    -- Cleaned Hours (Convert text/NULL to FLOAT 0.0)
    COALESCE(TRY_CAST(HRS_RN AS FLOAT), 0.0) AS RN_HOURS,
    COALESCE(TRY_CAST(HRS_LPN AS FLOAT), 0.0) AS LPN_HOURS,
    COALESCE(TRY_CAST(HRS_CNA AS FLOAT), 0.0) AS CNA_HOURS,
    COALESCE(TRY_CAST(HRS_MEDAIDE AS FLOAT), 0.0) AS MEDAIDE_HOURS,
    
    -- Total Direct Care Hours (RN + LPN + CNA + MedAide)
    (
        COALESCE(TRY_CAST(HRS_RN AS FLOAT), 0.0) + 
        COALESCE(TRY_CAST(HRS_LPN AS FLOAT), 0.0) + 
        COALESCE(TRY_CAST(HRS_CNA AS FLOAT), 0.0) + 
        COALESCE(TRY_CAST(HRS_MEDAIDE AS FLOAT), 0.0)
    ) AS TOTAL_DIRECT_CARE_HOURS,
    
    -- Safe HPRD Ratios (Hours Per Resident Day)
    CASE 
        WHEN COALESCE(TRY_CAST(MDSCENSUS AS NUMBER), 0) > 0 
        THEN ROUND(COALESCE(TRY_CAST(HRS_RN AS FLOAT), 0.0) / TRY_CAST(MDSCENSUS AS NUMBER), 2)
        ELSE 0.0 
    END AS RN_HPRD,
    
    CASE 
        WHEN COALESCE(TRY_CAST(MDSCENSUS AS NUMBER), 0) > 0 
        THEN ROUND((
            COALESCE(TRY_CAST(HRS_RN AS FLOAT), 0.0) + 
            COALESCE(TRY_CAST(HRS_LPN AS FLOAT), 0.0) + 
            COALESCE(TRY_CAST(HRS_CNA AS FLOAT), 0.0)
        ) / TRY_CAST(MDSCENSUS AS NUMBER), 2)
        ELSE 0.0 
    END AS TOTAL_NURSING_HPRD,
    
    -- Data Quality Flags from Bronze Audits
    CASE WHEN COALESCE(TRY_CAST(MDSCENSUS AS NUMBER), 0) = 0 THEN TRUE ELSE FALSE END AS IS_ZERO_CENSUS,
    CASE WHEN COALESCE(TRY_CAST(HRS_RN AS FLOAT), 0.0) > 500.0 THEN TRUE ELSE FALSE END AS IS_HIGH_RN_HOURS,
    CASE WHEN COALESCE(TRY_CAST(HRS_CNA AS FLOAT), 0.0) > 1000.0 THEN TRUE ELSE FALSE END AS IS_HIGH_CNA_HOURS,
    
    _SOURCE_FILE,
    CURRENT_TIMESTAMP() AS _LOADED_AT

FROM HEALTHCARE_DB.BRONZE.MASTER_CSV_BRONZE;


-- ============================================================================
-- STEP 4: VERIFY SILVER DATA
-- ============================================================================
SELECT * FROM HEALTHCARE_DB.SILVER.SILVER_MASTER_DIM_PROVIDER WHERE STATE = 'MD'AND COUNTY_NAME ='MONTGOMERY' LIMIT 10;
SELECT * FROM HEALTHCARE_DB.SILVER.SILVER_MASTER_FACT_DAILY_STAFFING LIMIT 10;

