USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE DATABASE HEALTHCARE_DB;
CREATE OR REPLACE SCHEMA HEALTHCARE_DB.RAW;

USE SCHEMA HEALTHCARE_DB.RAW;

CREATE OR REPLACE STORAGE INTEGRATION HEALTHCARE_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::568318157863:role/healthcarerole'
    STORAGE_ALLOWED_LOCATIONS = ('s3://healthcaremetricsproject/data/');

DESC INTEGRATION HEALTHCARE_INT; -- update the trust policy of the IAM role 

CREATE OR REPLACE STAGE HEALTHCARE_DB.RAW.HEALTHCARE_STAGE
    STORAGE_INTEGRATION = HEALTHCARE_INT
    URL = 's3://healthcaremetricsproject/data/';

ls @HEALTHCARE_DB.RAW.HEALTHCARE_STAGE; -- confirm all source datasets are present

CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  ENCODING = 'WINDOWS1252'
  REPLACE_INVALID_CHARACTERS = TRUE;

